### ISSUE TITLE
How about immigrate those guidelines to Gitbook?

### ISSUE THREAD

**Issue by kevinlee85** [elsewhencode/project-guidelines#25]
How about immigrate those guidelines to Gitbook?

**Comment by vpanjganj** [comment]
Gitbook does look fancy. However, I think the current way is much easier to read through. I used to love [John Papa Angular Style Guide](https://github.com/johnpapa/angular-styleguide/blob/master/a1/README.md) because of its simplicity. It is easily readable from top to bottom. I think when this document becomes more comprehensive gitbook will be the better approach.
